name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  main_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
      - name: npm install
        run: npm install
      - name: build-backend
        run: npm start-prod
      - name: build-frontend
        run: npm run build:frontend
      - name: lint
        run: npm run lint:frontend
      - name: test
        run: npm run test:frontend
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e:frontend
          start: npm run start-prod
          wait-on: http://localhost:3003
      - name: Deploy to Heroku
        #if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: fullstackblog-aapol
          heroku_email: aapo.leppanen@gmail.com
          healthcheck: https://fullstackblog-aapol.herokuapp.com/health
          rollbackonhealthcheckfailed: true
  tagging_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push the tag
        #if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
